<option value="DKK">Dansk Krone (DKK)</option>
<option value="EUR">Euro (EUR)</option>
<option value="USD">US Dollar (USD)</option>
<option value="JPY">Japansk Yen (JPY)</option>
<option value="BGN">Bulgarsk Lev (BGN)</option>
<option value="CZK">Tjekkisk Koruna (CZK)</option>
<option value="GBP">Britisk Pund Sterling (GBP)</option>
<option value="HUF">Ungarsk Forint (HUF)</option>
<option value="PLN">Polsk Zloty (PLN)</option>
<option value="RON">Rumænsk Leu (RON)</option>
<option value="SEK">Svensk Krone (SEK)</option>
<option value="CHF">Schweizisk Franc (CHF)</option>
<option value="ISK">Islandsk Króna (ISK)</option>
<option value="NOK">Norsk Krone (NOK)</option>
<option value="HRK">Kroatisk Kuna (HRK)</option>
<option value="RUB">Russisk Rubel (RUB)</option>
<option value="TRY">Tyrkisk Lira (TRY)</option>
<option value="AUD">Australsk Dollar (AUD)</option>
<option value="BRL">Brasiliansk Real (BRL)</option>
<option value="CAD">Canadisk Dollar (CAD)</option>
<option value="CNY">Kinesisk Yuan (CNY)</option>
<option value="HKD">Hong Kong Dollar (HKD)</option>
<option value="IDR">Indonesisk Rupiah (IDR)</option>
<option value="ILS">Israelsk Ny Shekel (ILS)</option>
<option value="INR">Indisk Rupee (INR)</option>
<option value="KRW">Sydkoreansk Won (KRW)</option>
<option value="MXN">Mexicansk Peso (MXN)</option>
<option value="MYR">Malaysisk Ringgit (MYR)</option>
<option value="NZD">New Zealandsk Dollar (NZD)</option>
<option value="PHP">Filippinsk Peso (PHP)</option>
<option value="SGD">Singapore Dollar (SGD)</option>
<option value="THB">Thailandsk Baht (THB)</option>
<option value="ZAR">Sydafrikansk Rand (ZAR)</option>
